version: '3.7'

services:
  development:
    stdin_open: true
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: react-ui
    ports:
      - "3000:3000"
    volumes:
      - "./ui:/usr/src/app/ui"
      - "/usr/src/app/ui/node_modules"

  flask_app_uwsgi:
    init: true
    build:
      context: ./server/application
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - slow_api_test

  slow_api_test:
    init: true
    build: ./server/slow_api_test
    environment:
      - ENDPOINT=4000
    expose:
      - "4000"


