version: '3.7'

services:
  react_development:
    stdin_open: true
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: react-ui
    ports:
      - "3000:3000"

  flask_development:
    init: true
    build:
      context: ./server/application
      dockerfile: Dockerfile
    container_name: flask-core
    environment:
      - THREADS=50
      - WORKERS=3
    ports:
      - "127.0.0.1:5000:5000"

  slow_api_test:
    init: true
    build: ./server/slow_api_test
    environment:
      - ENDPOINT=4000
    expose:
      - "4000"


