version: "3.7"
services:
  flask_app:
    init: true
    build:
      context: ./application
      dockerfile: Dockerfile-devserver
    environment:
      - PORT_APP=3000
      - PORT_API=4000
      - THREADS=without
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - slow_api_test

  flask_app_threaded: # extends: flask_app
    init: true
    build:
      context: ./application
      dockerfile: Dockerfile-devserver
    environment:
      - PORT_APP=3001
      - PORT_API=4000
      - THREADS=with
    ports:
      - "127.0.0.1:3001:3001"
    depends_on:
      - slow_api_test

  slow_api_test:
    init: true
    build: ./slow_api_test
    environment:
      - ENDPOINT=4000
    expose:
      - "4000"
